#服务器容器部署，应用端口统一覆盖为8080
server:
  port: 8080
spring:
  profiles:
    # 引用本地配置，文件夹区分
    include: datasource

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
