spring:
  # Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.249.62:30306/cloud?useUnicode=true&characterEncoding=utf8
    username: local_prd
    password: local_prd

